name: info8010
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.6
  - numpy
  - scipy
  - matplotlib
  - scikit-learn
  - jupyter
  - pytorch-cpu
  - torchvision-cpu
  - tensorboard
  - tensorboardX
  - pillow
